#ifndef CONSTANTS_STRING_LOGIC_CONSTANTS_HH_
#define CONSTANTS_STRING_LOGIC_CONSTANTS_HH_

#include <QString>

namespace logic_constants {

  static const QString SET_AUTOTRACE_OFF_("SET AUTOTRACE OFF");
  static const QString SET_AUTOTRACE_ON_EXPLAIN("SET AUTOTRACE ON EXPLAIN");
  static const QString SET_AUTOTRACE_ON_STATISTICS(
      "SET AUTOTRACE ON STATISTICS");
  static const QString SET_AUTOTRACE_ON("SET AUTOTRACE ON");
  static const QString SET_AUTOTRACE_TRACEONLY("SET AUTOTRACE TRACEONLY");
  static const QString SET_AUTOTRACE_ON_TRACEONLY_EXPLAIN(
      "SET AUTOTRACE ON TRACEONLY EXPLAIN");
  static const QString SET_AUTOTRACE_ON_TRACEONLY_STATS(
      "SET AUTOTRACE TRACEONLY ON STATISTICS");

}  // namespace logic_constants

#endif  // CONSTANTS_STRING_LOGIC_CONSTANTS_HH_
