#ifndef AUTOTRACE_SETTING_HH
#define AUTOTRACE_SETTING_HH

enum class AutotraceSetting {
    SET_AUTOTRACE_OFF,
    SET_AUTOTRACE_ON_EXPLAIN,
    SET_AUTOTRACE_ON_STATISTICS,
    SET_AUTOTRACE_ON,
    SET_AUTOTRACE_TRACEONLY,
    SET_AUTOTRACE_ON_TRACEONLY_EXPLAIN,
    SET_AUTOTRACE_ON_TRACEONLY_STATISTICS
};

#endif // AUTOTRACE_SETTING_HH
